<?php // This is where you add the page title, it also displays in the level 1 heading below
	$title = 'Report from the Chair'; 
	///////////////////////////////////////////////////
	include '../../includes/head.inc.php'; 
	?>
    
    <div class="container">
    	<div class="row">
			<?php include 'side-nav.php' ?>
        
		<div class="col-sm-8 col-xs-11 content" id="startContent">
			<h1><?php echo $title ?></h1>
	<p>
		The 2015–16 financial year marked a milestone for the Australian superannuation industry.
	</p>
	<p>
		The Government accepted the Financial System Inquiry’s recommended objective for superannuation: “to provide income in retirement to substitute or supplement the Age Pension”. The forthcoming legislation changes will see a shift in the focus of the superannuation industry from the accumulation of a lump sum balance to the provision of a retirement income for retirees. This change is consistent with CSC’s long-held objective of growing our members’ superannuation savings to help them to achieve an adequate income in their retirement.
	</p>
	<h2>Proposed changes to super</h2>
	<p>
		Major changes to Australia’s superannuation system were also proposed in the May 2016 Federal Budget, most of which were planned to take effect on 1 July 2017. Further announcements were made by the Government on 15 September 2016.
	</p>
	<p>
		If these changes are legislated, they will affect our members to varying degrees, dependent on where they are positioned in their work-life cycle and existing superannuation savings. CSC will continue to help members manage any changes through our Customer Information Centre, super scheme seminars and workshops, and fee-for-service personal financial advice services.
	</p>
	<h2>Investment performance in 2015–16</h2>
	<p>
		2015–16 challenged investment markets with a major decline in oil prices and doubts about the resilience of global economic growth. By considering these potential risks, in the context of our longer investment horizon, CSC was able to ensure that all of its investment options met or exceeded their net real return objectives over the three years to June 2016.
	</p>
	<p>
		That the shorter period of the 2015–16 financial year provided only modest investment returns was not overly surprising. CSC increased its allocation to defensive assets within its Balanced (default) and Aggressive options, in the middle of the financial year, in response to the ongoing challenges facing global policymakers and investment markets – specifically, lower levels of potential global economic growth, historically low interest rates, significant levels of debt, fully-valued asset prices and the potential for some market liquidity challenges. These actions partially insulated our portfolios from the weakness in equity markets in the latter half of 2015–16 and, importantly, provided CSC with the opportunity to buy back into equity markets, at lower prices, in the wake of the “Brexit” event, late in the financial year.
	</p>
	<p>
		It is important to remember that CSC takes a long-term approach to investment, to match our superannuation-member’s horizon. There will be periods – as we experienced in 2015–16 – where we take actions to limit the potential for capital loss, or where the returns available to prudent risk-taking, mean that our investment performance is lower than we would expect over the long-term.
	</p>
	<p>
		Our investment strategy has a keen focus on avoiding loss when we perceive risk to be elevated, so that the probability of achieving the investment objectives that are relevant to our members, over their time horizons, remains high. This means that, compared to other superannuation funds, we generally deliver greater preservation of our members’ balances through periods of negative investment returns.
	</p>
	<p>
		Over the long-run, as we preserve more capital in weak markets and capture most of the returns in strong markets, the cumulative return on our members’ superannuation balances will be very competitive and consistent.
	</p>
	<p>
		Indeed, over the past decade, when equity markets have been strong, our default investment options – in which nine out of 10 CSC superannuation members invest – performed healthily and, on average, captured up to 88% of the returns generated by the average Australian superannuation fund. In contrast, when equity markets were falling, our default portfolios avoided more than 48% of the negative returns delivered by the average Australian superannuation fund (ex the financial crisis).
	</p>
	<p>
		These default options have all achieved their investment return target of CPI plus 3.5% per annum after fees and taxes over the full seven year cycle to 30 June 2016 (table 1). This has been achieved within their risk limits, which constrain the number of negative returns in any 20 year period, to no more than three to four years.
	</p>
	<table class="scheme-table table">
		<caption>Table 1: CSC’s net investment performance for Default (ie Balanced) Options</caption>
		<thead>
			<tr>
				<th>&nbsp;</th>
				<th>1 year %</th>
				<th>3 years %</th>
				<th>5 years %</th>
				<th>7 years %</th>
			</tr>
		</thead>
		<tfoot>
			<td colspan="5"><strong>Note:</strong> Net of fees and taxes returns over periods of one, three, five and seven years to 30 June 2016.</td>
		</tfoot>
		<tbody class="five-or-more">
			<tr>
				<td>CSS</td>
				<td>1.9</td>
				<td>8.4</td>
				<td>8.2</td>
				<td>8.5</td>
			</tr>
			<tr>
				<td>PSS</td>
				<td>1.7</td>
				<td>8.3</td>
				<td>8.2</td>
				<td>8.4</td>
			</tr>
			<tr>
				<td>MilitarySuper</td>
				<td>1.9</td>
				<td>8.3</td>
				<td>7.3</td>
				<td>6.2</td>
			</tr>
			<tr>
				<td>PSSap</td>
				<td>1.8</td>
				<td>8.4</td>
				<td>8.2</td>
				<td>8.3</td>
			</tr>
		</tbody>
	</table>
	<p>
		<strong>CSC’s primary savings vehicle for postretirement members</strong>, the “Income-focused” option for our CSCri product, generated a robust 6.5% net return over 2015–16. This was well above its net return objective of CPI plus 2% per annum. And continues the strong performance history of this option, which has generated an average real return that is 3.1% per annum in excess of its real return objective over the last three years. This consistently strong performance reflects the option’s asset allocation management and its exposure to CSC’s direct, unlisted core property portfolio. </p>
	<p>
		Despite the potential for some cyclical variations in different regions, we expect the level of global economic growth and interest rates to remain low, on average, relative to the past three decades. This is likely to result from the combination of structural influences, like demographics and technological change, as well as lower reliance on credit. In such a world, it will be increasingly important for superannuants to consider not just their investment returns, but also their contribution rates and years in the workforce, when planning for their retirement.
	</p>
	<p>
		In this regard, CSC is focused on continuously improving our understanding of the unique characteristics of our member-base – demographics; account balances at different work-life phases; life-stage-fit investment option choices; and adequacy rates, as defined by ASFA’s “comfortable standard” in retirement. This helps us to refine and tailor our investment objectives and strategies to better service our unique member requirements.
	</p>
	<h2>A member focus</h2>
	<p>
		One of CSC’s key values is our “focus on members.” This value is reflected in all of our operations. The integration of CSC and defined-benefit scheme administrator, ComSuper, was a major focus of work in 2015–16. As a unified team, we can now work together to continually increase the efficiency with which we provide all of the services our members require to prepare well for, and be provided well for, in retirement.
	</p>
	<p>
		During the year we agreed five new values for CSC’s unified team (see box), with the first value being “focus on members.”
	</p>
	<p>
		We are also very conscious of how complex and confusing superannuation can seem. Our strategic objectives include supporting our members to make sound decisions about their own retirement choices, easily and with confidence.
	</p>
	<p>
		Consistent with this strategic intent, CSC offers only three pre-mixed investment options, which represent each of the critical stages in the journey towards retirement adequacy for our members.
	</p>
	<div class="callout bg-success">
	<h2>CSC values</h2>
		<h3>Focus On Members</h3>
			<p>Members’ interests are our business.</p>
		<h3>Think Boldly</h3>
			<p>We improve business outcomes by encouraging creativity and innovation.</p>
		<h3>Be Fair</h3>
			<p>We treat others how we wish to be treated.</p>
		<h3>Listen Openly and Talk Straight</h3>
			<p>We communicate respectfully and honestly.</p>
		<h3>Work Together</h3>
			<p>We work in a supportive and collaborative way.</p>
	</div>
	<h2>Giving our members reasons to choose CSC</h2>
		<p>
			While all of our superannuation members are, or have been, Australian Public Service or ADF employees, most of them have a choice in where to invest their superannuation. CSC strives to be an industry leader and a natural choice for our members.
		</p>
		<p>
			Our organisation actively supports innovation and encourages all of our employees to be constantly thinking about ways to ensure that CSC is a best-practice provider of investment returns and superannuation services to our members.
		</p>
		<p>Over 2015–16, this intent was reflected in:</p>
			<ul>
				<li>Initiation of upgrades to our IT platforms, to support increased operational flexibility and more robust administration of our defined-benefit schemes.</li>
				<li>Investment in both our human and technology capital, to increase our ability to understand the defining characteristics of our members better, and support tailoring of our products and services.</li>
				<li>Streamlining of our internal communication processes and systems to increase the speed and efficiency with which we can respond to our member enquiries.</li>
				<li>Reviewing our external communication platforms, to the same ends.</li>
			</ul>
		<h2>New products and services</h2>
			<p>
				CSC worked closely with the Government in 2015–16 on the development of two new military super schemes – ADF Super and ADF Cover. These new super schemes commenced on 1 July 2016 so ADF entrants can now choose to join ADF Super. This reform also meant the closure of the MilitarySuper defined benefit scheme to new members on 30 June 2016.
			</p>
			<p>
				The two new military super schemes increase the number of super schemes that CSC manages on behalf of current and former ADF members and public sector employees to 11.
			</p>
			<p>
				In May 2016, the Government announced that PSSap scheme members who leave Commonwealth employment, may continue to contribute to PSSap. This is a very important and welcome reform because it removes a constraint on our members by enabling them to continue to choose CSC as their superannuation provider, should they wish to do so, if their employment within the public sector is interrupted or ends.
			</p>
		<h2>CSC Board of directors</h2>
			<p>
				Three changes were made to the CSC Board at the end of 2015–16. The terms of Mr John McCullagh, Dr Michael Vertigan and Mr Peter Feltham ended on 30 June 2016. The term of Ms Lyn Gearing ended on 12 September 2016. I would like to take this opportunity to thank John, Michael, Peter and Lyn for the professionalism and dedication they demonstrated throughout their terms. The skills, knowledge and experience which they brought to Board discussions and decisions made a significant contribution to our members, by helping the Board achieve its strategic milestones during their terms.
			</p>
			<p>
				I welcome our new CSC Board members – Mr Garry Hounsell, Mr Sunil Kemppi, Air Vice Marshal Tony Needham (all of whom commenced on 1 July 2016), and Mrs Ariane Barker (who commenced on 13 September 2016). Their appointments mean that the Board continues to have a diverse mix of directors with the relevant skills and experience to effectively govern CSC, the administration of complex schemes and the $37 billion in funds we manage on behalf of our members.
			</p>
			<p>
				I would also take the opportunity to extend my thanks to all of the CSC Board of directors and staff who worked effectively and collegiately throughout the past year, to deal constructively with intense organisational-structure change and challenging investment markets.
			</p>
			<p>
				And, as always, on behalf of everyone at CSC, I thank our more than 725,000 superannuation members and pensioners for their continued trust in CSC as the guardian of their superannuation funds – a responsibility we all take very seriously.
			</p>
			<img src="../../images/pc_signature.jpg" alt="signature of Patricia Cross, Chairman">
			<p>
				Patricia Cross<br>
				Chair
			</p>

	<ul class="bottomnav">
    <li><a href="../introduction/about-csc-members.php" class="back">Previous &#8211; About CSC members</a></li><li><a href="#topnav" class="top">Top</a></li><li><a href="csc-major-achievment.php" class="next">Next &#8211; CSC's major achievements</a></li>
	</ul>
	
	<div class="btn-group" role="group">
    <button type="button" class="btn btn-default"><a href="../introduction/about-csc-members.php" class="back">Previous </a></button>
	<button type="button" class="btn btn-default"><a href="#topnav" class="top">Top</a></button>
	<button type="button" class="btn btn-default"><a href="csc-major-achievment.php" class="next">Next</a></button>
	</div>
	
</div>
</div>
</div>
        
<?php include '../../includes/footer.inc.php'; ?>